language: ruby

install:
  - sudo apt-get update
  - gem install appium_lib
  - curl "https://www.browserstack.com/app-automate/sample-apps/android/WikipediaSample.apk" -o "$TRAVIS_BUILD_DIR/WikipediaSample.apk"

script:
  - echo $BROWSERSTACK_APP_ID
  - ruby android/single_test.rb

addons:
  browserstack:
    username: 'pankajahuja1'
    access_key:
      secure: 'QEma8cjUb0xFi8r861DHATd3nHTUaeKua8k4WdGT9n5x0gIztDvkzKXVygHUWGDvZqypA/7ZqYKQWl/bMYKe29O9ML0kmpP0NC6eRd3AIJRMgf6wjL6gL1aSjlGKDxeFSZVW20nODO9MVAeH/gNMxk6kG3sDOa0XHGvxIPiw9QDnxuIzGW6YAlSBe9l74+/feYurwPRrk3I9ym1MkTn3m6pPxl/rcfXW08Wtq+iohpF4/k1AL6+wIzNf0AhAoKTwEBS1j0ttgeztrOgPacqPxYewVlKen9mktfsd2sUjk5HZN7H9DmyRtNV3nzo6x7oZTSUqRo/1gYCf3qNCiC9TMGQ12SNm66CPgwf2PzqCA6ISY9YuJqkuumJPFLsIe2f7AJ/dsMmbS9anOGgu2gKUoorqSlQwbh5hEcTCZK9MyF3UxV7L+61kSC92DFRhPuc3rI4ttyQpkKuIMfqE1iUgAxakmdQL3DezkJW+SHzquCx7U70JTFH+ZstCLPLn7W+MJH+Cp6fDC5fEVfQaXADkQyiNuTjk+9V0HgAS5ywsgQ7zd0ulbeGR2IKYE062qysjLlZLb0J/El5vsO2xiTrRCHJsc9ylS5T68eez0JsXLBEaymDF05x1kw0EPXZ3RPovp8AnIQf6ToG7HAU/h9b/0OYvplXwi7CyH6FXzfimxBA='
    app_path: 'WikipediaSample.apk'
